FROM node:14

# Create app directory
WORKDIR /django_react

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

COPY package*.json ./
COPY .babelrc ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3000

