version: "3.3"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.django.dev
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_react
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nodejs.dev
    command: bash -c "npm install && npm run start:dev"
    volumes:
      - .:/django_react
    ports:
      - "3000:3000"


