# Use an official Python runtime as a parent image (image to start)
FROM python:3.8-slim-buster

ENV PYTHONUNBUFFERED=1

# Set the working directory to /app
WORKDIR /django_react

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
